<a href="https://colab.research.google.com/github/muhammadsajad/PyTorch-Learning/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# create model class

import torch
import torch.nn as nn

In [4]:
class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self,features):
    out=self.linear(features)
    out=self.sigmoid(out)

    return out


In [5]:
# create datasset
features=torch.rand(10,5)

# create model
model=Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.7061],
        [0.5998],
        [0.6029],
        [0.5925],
        [0.5796],
        [0.5872],
        [0.5667],
        [0.6382],
        [0.5921],
        [0.5888]], grad_fn=<SigmoidBackward0>)

In [6]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.3147,  0.3209,  0.4353,  0.3899, -0.3508]], requires_grad=True)

In [7]:
model.linear.bias

Parameter containing:
tensor([-0.3312], requires_grad=True)

In [8]:
! pip install torchinfo

In [10]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [11]:
# Creating a class for litle complcated model

class Model2(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.linear1=nn.Linear(num_features,3)
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmiod=nn.Sigmoid()

  def forward(self,features):

    out=self.linear1(features)
    out=self.relu(out)
    out=self.linear2(out)
    out=self.sigmiod(out)

    return out


In [12]:
model2=Model2(features.shape[1])
model2(features)

tensor([[0.4811],
        [0.5084],
        [0.5040],
        [0.4877],
        [0.5163],
        [0.5025],
        [0.4787],
        [0.5019],
        [0.4660],
        [0.5051]], grad_fn=<SigmoidBackward0>)

In [13]:
model2.linear1.weight

Parameter containing:
tensor([[-0.2560,  0.2744, -0.0547, -0.0490,  0.2565],
        [-0.0873,  0.1222,  0.3100,  0.0368,  0.0159],
        [-0.0046,  0.2143, -0.1242,  0.1646, -0.2528]], requires_grad=True)

In [14]:
model2.linear2.weight

Parameter containing:
tensor([[ 0.4756, -0.2716,  0.2204]], requires_grad=True)

In [16]:
model2.linear1.bias

Parameter containing:
tensor([ 0.0784,  0.0793, -0.1444], requires_grad=True)

In [17]:
model2.linear2.bias

Parameter containing:
tensor([-0.0253], requires_grad=True)

In [19]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [6]:
# Creating class for using Sequential container

class ModelContainer(nn.Module):

  def __init__(self,num_features):

    super().__init__()

    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):

    out=self.network(features)

    return out

In [7]:
model=ModelContainer(features.shape[1])
model(features)

tensor([[0.5679],
        [0.5988],
        [0.5999],
        [0.5908],
        [0.5939],
        [0.6061],
        [0.6061],
        [0.5905],
        [0.5918],
        [0.5984]], grad_fn=<SigmoidBackward0>)