<a href="https://colab.research.google.com/github/muhammadsajad/PyTorch-Learning/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.11.0+cu128


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")
else:
  print("GPU is not available. Using CPU")


GPU is not available. Using CPU


In [ ]:
# using empty
a=torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
torch.rand(2,3)

tensor([[0.2955, 0.1233, 0.8221],
        [0.1284, 0.7500, 0.5383]])

In [ ]:
# use of seed
torch.rand(2,3)

tensor([[0.6929, 0.8431, 0.9678],
        [0.3720, 0.2915, 0.4829]])

In [ ]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways
# arange
print("using arange ->", torch.arange(0,10))

# using linspace
print("using linspace ->",torch.linspace(0,10,10))

# using eye
print("using eye ->",torch.eye(5)) #identity matrix

# using full
print("using full ->", torch.full((3,3),5))

using arange -> tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **Tensor Shapes**

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[134434584563072,       364307936,        11312256],
        [       11312256, 134433513703680,        11325096]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# **Tensor Data Types**

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# **Mathematical operations**



# 1.   Scalar Operations



In [ ]:
x=torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [ ]:
# addition
x +2

# subtraction
x-2

# multiplication
x*3

# division
x/3

# int division
(x*100)//3

# mod
((x*100)//3)%2

# power
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])


# **2.   Element wise operation**

In [ ]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])
tensor([[0.0169, 0.2209, 0.9535],
        [0.7064, 0.1629, 0.8902]])


In [ ]:
# add
a+b

# sub
a-b

# multiply
a*b

# division
a/b
# power
a**b

# mod
a% b

tensor([[0.0060, 0.0377, 0.5277],
        [0.2472, 0.1394, 0.4235]])

In [ ]:
c=torch.tensor([1,-2,3,-4])

In [ ]:
 # abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# clamp


# **3.   Reduction operation**

In [ ]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[1., 0., 6.],
        [3., 8., 1.]])

In [ ]:
# sum
torch.sum(e)

tensor(34)

In [ ]:
# sum along columns
torch.sum(e,dim=0)

tensor([ 9,  9, 16])

In [ ]:
# sum along rows
torch.sum(e,dim=1)

tensor([16, 18])

In [ ]:
# mean
torch.mean(e)

tensor(4.)

In [ ]:
# mean along column
torch.mean(e,dim=0)

tensor([5.5000, 4.5000, 2.0000])

In [ ]:
# median
torch.median(e)

tensor(3.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# product
torch.prod(e)

tensor(34020.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.5626)

In [ ]:
# variance
torch.var(e)

tensor(6.5667)

In [ ]:
# argmax
torch.argmax(e)

tensor(4)

In [ ]:
# argmin
torch.argmin(e)

tensor(1)

# **4. Matrix operations**

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

print(f)
print(g)

tensor([[6, 0, 3],
        [8, 9, 1]])
tensor([[9, 4],
        [4, 6],
        [2, 2]])


In [ ]:
# matrix multiplication
torch.matmul(f,g)

tensor([[ 60,  30],
        [110,  88]])

In [ ]:
vector1=torch.tensor([2,2])
vector2=torch.tensor([3,4])

# dot product
torch.dot(vector1,vector2)

tensor(14)

In [ ]:
f

tensor([[6, 0, 3],
        [8, 9, 1]])

In [ ]:
# transpose
torch.transpose(f,0,1)

tensor([[6, 8],
        [0, 9],
        [3, 1]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 1., 5.],
        [9., 1., 9.],
        [6., 2., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(18.0000)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.6111,  0.1667,  0.2222],
        [-0.5000, -0.5000,  1.0000],
        [ 0.6667,  0.0000, -0.3333]])

# **5. Comparison Operations**

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)

print(i)
print(j)

tensor([[2, 9, 1],
        [3, 7, 0]])
tensor([[8, 1, 0],
        [7, 2, 0]])


In [ ]:
# greater than
i>j

# less than
i<j

# equal to
i==j

# not equal to
i!=j

# greater than equal to
i>=j

# less than equal to
i<=j

tensor([[ True, False, False],
        [ True, False,  True]])

# **6. Special functions**

In [ ]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[3., 0., 9.],
        [1., 0., 6.]])

In [ ]:
# log
torch.log(k)

tensor([[0.0000, 1.7918, 1.3863],
        [0.0000, 1.6094, 0.0000]])

In [ ]:
# exp
torch.exp(k)

tensor([[  2.7183, 403.4288,  54.5981],
        [  2.7183, 148.4132,   2.7183]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.0000, 2.4495, 2.0000],
        [1.0000, 2.2361, 1.0000]])

In [ ]:
# sigmiod
torch.sigmoid(k)

tensor([[0.7311, 0.9975, 0.9820],
        [0.7311, 0.9933, 0.7311]])

In [ ]:
# softmax
torch.softmax(k,dim=0)

tensor([[0.8808, 0.5000, 0.9526],
        [0.1192, 0.5000, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[3., 0., 9.],
        [1., 0., 6.]])

# **7. Inplace Operations**

In [ ]:
m=torch.rand(2,3)
n=torch.rand(2,3)

print(m)
print(n)

tensor([[0.7061, 0.2358, 0.4638],
        [0.5777, 0.0833, 0.4074]])
tensor([[0.4996, 0.1257, 0.3695],
        [0.8950, 0.8732, 0.3441]])


In [ ]:
m.add_(n)

tensor([[1.2057, 0.3615, 0.8333],
        [1.4727, 0.9566, 0.7514]])

In [ ]:
m

tensor([[1.2057, 0.3615, 0.8333],
        [1.4727, 0.9566, 0.7514]])

In [ ]:
n

tensor([[0.4996, 0.1257, 0.3695],
        [0.8950, 0.8732, 0.3441]])

In [ ]:
m.relu_()

tensor([[1.2057, 0.3615, 0.8333],
        [1.4727, 0.9566, 0.7514]])

In [ ]:
m

tensor([[1.2057, 0.3615, 0.8333],
        [1.4727, 0.9566, 0.7514]])

# **8. Copying a Tensor**

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.5731, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
b=a

In [ ]:
b

tensor([[0.5731, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
a[0][0]=0

In [ ]:
a

tensor([[0.0000, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
b

tensor([[0.0000, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
id(a)

137957404955648

In [ ]:
id(b)

137957404955648

In [ ]:
b=a.clone()

In [ ]:
a

tensor([[0.0000, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
b

tensor([[0.0000, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
a[0][0]=10

In [ ]:
a

tensor([[10.0000,  0.2649,  0.8138],
        [ 0.7641,  0.7658,  0.1814]])

In [ ]:
b

tensor([[0.0000, 0.2649, 0.8138],
        [0.7641, 0.7658, 0.1814]])

In [ ]:
id(a)

137957404955648

In [ ]:
id(b)

137957062387552

# **9. Tensor Operations on GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda')

In [ ]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.6457, 0.4838, 0.6298],
        [0.5807, 0.5644, 0.0034]], device='cuda:0')

In [ ]:
# moving an existing tensor to GPU
a=torch.rand(2,3)
a

tensor([[0.6549, 0.3350, 0.3080],
        [0.2714, 0.0891, 0.9157]])

In [ ]:
b=a.to(device)

In [ ]:
b+5

tensor([[5.6549, 5.3350, 5.3080],
        [5.2714, 5.0891, 5.9157]], device='cuda:0')

# **10. Reshaping Tensors**

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
# flattten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.7905, 0.1049, 0.4521, 0.9196],
         [0.2532, 0.5454, 0.3286, 0.2859],
         [0.0649, 0.1600, 0.4100, 0.2120]],

        [[0.6297, 0.8372, 0.2715, 0.1886],
         [0.6329, 0.2957, 0.6570, 0.5549],
         [0.7345, 0.2084, 0.4311, 0.4948]]])

In [ ]:
# permut
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [ ]:
# unsqueeze

c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# **11. Numpy and Pytorch**

In [ ]:
import numpy as np

In [ ]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [ ]:
b=a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [ ]:
torch.from_numpy(c)

tensor([1, 2, 3])

In [ ]:
type(c)

numpy.ndarray